version: 0.2
phases:
  install:
    commands:
      - npm install
  # pre_build:
  #   commands:
  #     - npm test
  build:
    commands:
      - npm run build
artifacts:
  base-directory: dist
  files:
    - '**/*'
  name: $(date +%Y-%m-%d)-$CODEBUILD_SOURCE_VERSION-$(echo $CODEBUILD_BUILD_ID | sed -e 's/:/-/g').zip