---
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
  sonarcloud: sonarsource/sonarcloud@1.0.1

docker_images: &docker_images
  docker:
    - image: circleci/node:dubnium
  working_directory: ~/deploy

push_to_artifactory: &push_to_artifactory
  - run:
      name: Push Artifacts
      command: .circleci/store_artifacts.sh

pe_fe_env_vars: &env_vars
  environment:
    # APP_VERBOSE_ERRORS: "false"
    # PAYMENT_ENABLED: "false"
    # BOOKINGS_ON_REQUEST: "false"
    # DRIFT_APP_ID: b5ivt3e4xa3w
    # DRIFT_ENABLED_ROLES: ta

jobs:
  deploy_develop:
    <<: *docker_images
    <<: *env_vars
    environment:
      NODE_ENV: develop
      APP_ENV: develop
      API_BASE_URL: https://client-api.qa.pure-escapes.com
      ADMIN_BASE_URL: https://qa.pure-escapes.com/admin
      BACKEND_BASE_URL: https://api.qa.pure-escapes.com/api
      S3_ARTIFACT_PATH: s3://pure-artifactory/qa/webapp-frontend
      SENTRY_DSN: https://42cd1925ee694672b41e177c3edda033@o300001.ingest.sentry.io/5235948
      SENTRY_ENV: qa
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Auth with NPM private registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: build react app
          command: yarn && yarn run build:dev
      - run:
          name: Run tests
          command: yarn test:ci
      - store_artifacts:
          path: tests/coverage
      - store_test_results:
          path: tests/coverage
      - aws-cli/setup:
          profile-name: default
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          .circleci/do-exclusively.sh aws s3 sync ./dist s3://qa.pure-escapes.com \
            --acl public-read --delete --exclude "admin/*" \
            --cache-control max-age=31536000
      - run: |
          .circleci/do-exclusively.sh aws cloudfront create-invalidation \
              --distribution-id E3DKVF7CKJKFV \
              --paths /\*
      - <<: *push_to_artifactory
      - sonarcloud/scan
  deploy_sandbox:
    <<: *docker_images
    <<: *env_vars
    environment:
      NODE_ENV: develop
      APP_ENV: develop
      API_BASE_URL: https://client-api.sandbox.pure-escapes.com
      ADMIN_BASE_URL: https://sandbox.pure-escapes.com/admin
      BACKEND_BASE_URL: https://api.sandbox.pure-escapes.com/api
      S3_ARTIFACT_PATH: s3://pure-artifactory/sandbox/webapp-frontend
      SENTRY_DSN: https://42cd1925ee694672b41e177c3edda033@o300001.ingest.sentry.io/5235948
      SENTRY_ENV: sandbox
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Auth with NPM private registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: build react app
          command: yarn && yarn build:dev
      - run:
          name: Run tests
          command: yarn test:ci
      - aws-cli/setup:
          profile-name: default
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          .circleci/do-exclusively.sh aws s3 sync ./dist s3://sandbox.pure-escapes.com \
            --acl public-read --delete \
            --cache-control max-age=31536000
      - run: |
          .circleci/do-exclusively.sh aws cloudfront create-invalidation \
              --distribution-id E73FC4CF0OSGY \
              --paths /\*
      - <<: *push_to_artifactory
  deploy_demo:
    <<: *docker_images
    <<: *env_vars
    environment:
      NODE_ENV: develop
      APP_ENV: develop
      API_BASE_URL: https://client-api.demo.pure-escapes.com
      ADMIN_BASE_URL: https://demo.pure-escapes.com/admin
      BACKEND_BASE_URL: https://api.demo.pure-escapes.com/api
      S3_ARTIFACT_PATH: s3://pure-artifactory/demo/webapp-frontend
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Auth with NPM private registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: build react app
          command: yarn && yarn build:dev
      - run:
          name: Run tests
          command: yarn test:ci
      - aws-cli/setup:
          profile-name: default
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          .circleci/do-exclusively.sh aws s3 sync ./dist s3://demo.pure-escapes.com \
            --acl public-read --delete \
            --cache-control max-age=31536000
      - run: |
          .circleci/do-exclusively.sh aws cloudfront create-invalidation \
              --distribution-id E6HAGBWZNMVV2 \
              --paths /\*
      - <<: *push_to_artifactory
  deploy_master:
    <<: *docker_images
    <<: *env_vars
    environment:
      NODE_ENV: production
      APP_ENV: production
      API_BASE_URL: https://client-api.production.pure-escapes.com
      ADMIN_BASE_URL: https://production.pure-escapes.com/admin
      BACKEND_BASE_URL: https://api.production.pure-escapes.com/api
      S3_ARTIFACT_PATH: s3://pure-artifactory/production/webapp-frontend
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Auth with NPM private registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: build react app
          command: yarn && yarn build
      - aws-cli/setup:
          profile-name: default
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          .circleci/do-exclusively.sh aws s3 sync ./dist s3://production.pure-escapes.com \
            --acl public-read --delete \
            --cache-control max-age=31536000
      - run: |
          .circleci/do-exclusively.sh aws cloudfront create-invalidation \
              --distribution-id E1ZNSARBE2K0BC \
              --paths /\*
      - <<: *push_to_artifactory

workflows:
  build_and_deploy:
    jobs:
      - deploy_approval:
          type: approval
          filters:
            branches:
              only:
                - develop
                - sandbox
                - demo
                - master
      - deploy_develop:
          requires:
            - deploy_approval
          context: deployments
          filters:
            branches:
              only:
                - develop
      - deploy_sandbox:
          requires:
            - deploy_approval
          context: deployments
          filters:
            branches:
              only:
                - sandbox
      - deploy_demo:
          requires:
            - deploy_approval
          context: deployments
          filters:
            branches:
              only:
                - demo
      - deploy_master:
          requires:
            - deploy_approval
          context: Production
          filters:
            branches:
              only:
                - master
