---
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16

docker_images: &docker_images
  docker:
    - image: circleci/node:dubnium
  working_directory: ~/deploy

pe_fe_env_vars: &env_vars
  environment:
    # APP_VERBOSE_ERRORS: "false"
    # PAYMENT_ENABLED: "false"
    # BOOKINGS_ON_REQUEST: "false"
    # DRIFT_APP_ID: b5ivt3e4xa3w
    # DRIFT_ENABLED_ROLES: ta

jobs:
  deploy_develop:
    <<: *docker_images
    <<: *env_vars
    environment:
      NODE_ENV: develop
      APP_ENV: develop
      API_BASE_URL: https://client-api.qa.pure-escapes.com
      ADMIN_BASE_URL: https://qa.pure-escapes.com/admin
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Auth with NPM private registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: build react app
          command: yarn && yarn run build:dev
      - run:
          name: Run tests
          command: yarn test:ci
      - aws-cli/setup:
          profile-name: default
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          aws s3 sync ./dist s3://qa.pure-escapes.com \
            --acl public-read --delete --exclude "admin/*" \
            --cache-control max-age=31536000
      - run: |
          aws cloudfront create-invalidation \
              --distribution-id E3DKVF7CKJKFV \
              --paths /\*
  deploy_sandbox:
    <<: *docker_images
    <<: *env_vars
    environment:
      NODE_ENV: develop
      APP_ENV: develop
      API_BASE_URL: https://client-api.sandbox.pure-escapes.com
      ADMIN_BASE_URL: https://sandbox.pure-escapes.com/admin
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Auth with NPM private registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: build react app
          command: yarn && yarn build:dev
      - run:
          name: Run tests
          command: yarn test:ci
      - aws-cli/setup:
          profile-name: default
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          aws s3 sync ./dist s3://sandbox.pure-escapes.com \
            --acl public-read --delete \
            --cache-control max-age=31536000
      - run: |
          aws cloudfront create-invalidation \
              --distribution-id E73FC4CF0OSGY \
              --paths /\*
  deploy_demo:
    <<: *docker_images
    <<: *env_vars
    environment:
      NODE_ENV: develop
      APP_ENV: develop
      API_BASE_URL: https://client-api.demo.pure-escapes.com
      ADMIN_BASE_URL: https://demo.pure-escapes.com/admin
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Auth with NPM private registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: build react app
          command: yarn && yarn build:dev
      - run:
          name: Run tests
          command: yarn test:ci
      - aws-cli/setup:
          profile-name: default
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          aws s3 sync ./dist s3://demo.pure-escapes.com \
            --acl public-read --delete \
            --cache-control max-age=31536000
      - run: |
          aws cloudfront create-invalidation \
              --distribution-id E6HAGBWZNMVV2 \
              --paths /\*
  deploy_master:
    <<: *docker_images
    <<: *env_vars
    environment:
      NODE_ENV: production
      APP_ENV: production
      API_BASE_URL: https://client-api.production.pure-escapes.com
      ADMIN_BASE_URL: https://production.pure-escapes.com/admin
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Auth with NPM private registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: build react app
          command: yarn && yarn build
      - aws-cli/setup:
          profile-name: default
      - run: |
          aws configure set preview.cloudfront true
      - run: |
          aws s3 sync ./dist s3://production.pure-escapes.com \
            --acl public-read --delete \
            --cache-control max-age=31536000
      - run: |
          aws cloudfront create-invalidation \
              --distribution-id E1ZNSARBE2K0BC \
              --paths /\*
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_develop:
          context: deployments
          filters:
            branches:
              only:
                - develop
      - deploy_sandbox:
          context: deployments
          requires:
            - deploy_develop
      - deploy_demo:
          context: deployments
          filters:
            branches:
              only:
                - demo
      - deploy_master:
          context: Production
          filters:
            branches:
              only:
                - master
