import PropTypes from 'prop-types';

import { noop } from 'utils';

export const propTypes = {
  addHoldLabel: PropTypes.bool,
  booking: PropTypes.object,
  bookLabel: PropTypes.string,
  canBook: PropTypes.bool,
  canChangeDates: PropTypes.bool,
  canEdit: PropTypes.bool,
  children: PropTypes.func,
  className: PropTypes.string,
  compact: PropTypes.bool,
  editGuardContent: PropTypes.any,
  guardEdit: PropTypes.bool,
  holdOnly: PropTypes.bool,
  hotel: PropTypes.object,
  name: PropTypes.string,
  onAddHolds: PropTypes.oneOfType([PropTypes.func, PropTypes.bool]),
  onBook: PropTypes.func,
  onGuardEdit: PropTypes.func,
  onReleaseHolds: PropTypes.oneOfType([PropTypes.func, PropTypes.bool]),
  onSubmit: PropTypes.func,
  releaseHoldLabel: PropTypes.bool,
  saving: PropTypes.number,
  showAddHolds: PropTypes.bool,
  showBookNow: PropTypes.bool,
  showDiscountedPrice: PropTypes.bool,
  showFullTotal: PropTypes.bool,
  showHolds: PropTypes.bool,
  showOriginalTotal: PropTypes.bool,
  showReleaseHolds: PropTypes.bool,
  showRoomImage: PropTypes.bool,
  summaryOnly: PropTypes.bool,
  total: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
};

export const defaultProps = {
  booking: {},
  canChangeDates: true,
  canEdit: true,
  children: noop,
  compact: false,
  guardEdit: false,
  holdOnly: false,
  hotel: {},
  onBook: noop,
  onGuardEdit: () => Promise.resolve(),
  onGuardEditComplete: () => Promise.resolve(),
  onSubmit: noop,
  showRoomImage: true,
  summaryOnly: false,
  total: 0,
  showHolds: false,
  onReleaseHolds: noop,
  onAddHolds: noop,
  showBookNow: true,
  showAddHolds: false,
  showReleaseHolds: false,
  showOriginalTotal: false,
  showDiscountedPrice: true,
};
